language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "12"
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: page
  edge: true
  spkip-cleanup: true
  keep-history: true
  keep-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit-message: "Deploy Release"
  on:
    branch: master
